/**:
  ros__parameters:
    # RTAB-Map parameters
    Rtabmap/LoopThr: "0.2"
    Rtabmap/LoopRatio: "0.2"
    RGBD/AngularUpdate: "0.01"
    RGBD/LinearUpdate: "0.01"
    RGBD/OptimizeFromGraphEnd: "false"
    RGBD/LoopCovLimited: "false"
    RGBD/OptimizeMaxError: "2.0"
    Vis/CorNNDR: "0.7"
    Vis/MinInliers: "30"
    Vis/MinInliersDistribution: "0.0"
    Vis/MaxFeatures: "1000"
    Kp/NndrRatio: "0.7"
    Kp/BadSignRatio: "0.5"
    Kp/MaxFeatures: "600"
    Grid/MaxGroundHeight: "0.0"
    Grid/MaxObstacleHeight: "0.0"
    Grid/RangeMax: "5.0"
    Grid/NoiseFilteringMinNeighbors: "5"
    Grid/RayTracing: "true"
    Grid/FromDepth: "true"
    Mem/DepthCompressionFormat: ".png"
    Mem/SaveDepth16Format: "false"
    Mem/BadSignaturesIgnored: "false"
    Optimizer/GravityConstraints: "true"
